server:
  port: 8003
cloud:
  serviceUrl: http://127.0.0.1:8000/eureka/

spring:
  application:
    name: cloud-logger-service   # 注册到 Eureka Server 上的应用名称

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true # 将自己的IP 注册到Eureka Server
  client:
    service-url:
      defaultZone: ${cloud.serviceUrl}
